### ISSUE TITLE
[$injector:unpr] Unknown provider: tProvider <- t <- notificationsBarDirective

### ISSUE THREAD

**Issue by mwq27** [alexbeletsky/ng-notifications-bar#30]
When I uglify my bower dependencies, I'm getting this error from the notificationsBar.

**Comment by mrdivyansh** [comment]
I have also same problem

**Comment by alexbeletsky** [comment]
I've just merged the fix from @mrdivyansh, version `ng-notifications-bar@0.0.15` published.
