### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by KonstantinYegupov** [alexbeletsky/ng-notifications-bar#45]
Note that the closing square bracket `]` appears twice below (first appearance should be removed):

    app.config(['notificationsConfigProvider'], function (notificationsConfigProvider) {
        // auto hide
        notificationsConfigProvider.setAutoHide(true)
    
        // delay before hide
        notificationsConfigProvider.setHideDelay(3000)
    }])

**Comment by alexbeletsky** [comment]
Just merged pull #39, where it's fixed.
