### ISSUE TITLE
TypeError: notificationsConfigProvider.setAutoHideAnimation is not a function

### ISSUE THREAD

**Issue by jonaszuberbuehler** [alexbeletsky/ng-notifications-bar#46]
Hi

Any plan on tagging a new release to make autoHideAnimation & autoHideAnimationDelay available over bower?

Thank you
--jonas

**Comment by HenrikFricke** [comment]
+1

**Comment by raiseandfall** [comment]
+1

Also the documentation in markdown should follow the last release version on NPM / Bower that does have the following methods : 
```

**Comment by raiseandfall** [comment]
+1

The documentation for the current version (0.0.15) on NPM & Bower is not following the last released API. Right now it says that the following methods are available where they are actually not part of the build yet : 
```
notificationsConfigProvider.setAutoHideAnimation()
notificationsConfigProvider.setAutoHideAnimationDelay()
```

Thanks

**Comment by handonam** [comment]
Can we update the NPM/Bower for this?  I have to install via github at the moment.

`npm install git://github.com/alexbeletsky/ng-notifications-bar.git --save`

I'm not familiar with how to update the npm.  I would assume you just bump up the build version numbers?

**Comment by alexbeletsky** [comment]
Hey guys, sorry for such a huge delay. Both npm and bower pushed.

If any issues, please let me know.

**Comment by lionelaza** [comment]
How to update bower install to fix this problem?

**Comment by jonaszuberbuehler** [comment]
Thx!
